### PR TITLE
Added tests for verifier type checking.

### PR DESCRIPTION
**Pull request by angusholder**
I'm not sure if I'm missing something or if I've found a bug in filetests, it doesn't like my error directive on the jump instruction, which is identical to the one on the line before on the branch instruction.

### CODE REVIEW

**Comment by stoklund** [comment]
I'll try to reproduce here.

**Comment by stoklund** [comment]
I'm getting this failure:

```
FAIL filetests/verifier/type_check.cton: verifier(jump_args): cannot handle multiple error: directives
```

The `test verifier` command will only accept one `error:` directive per function. That is because the verifier is only capable of returning a single failure. There is no way it can report an error for both instructions, even if they both have errors.

**Comment by angusholder** [comment]
Ah of course, sorry that makes sense

**Comment by stoklund** [comment]
FWIW, it would be pretty cool if the verifier were capable of reporting multiple errors at a time.

**Comment by stoklund** [comment]
Landed in 874f95dc2ac24476d1441093442b3e09c5274abc with some updates.

Thanks!

**Pull request closed without merging**
