### PR TITLE
Implement simple JSON serialization for Cretonne IL.

### PR DESCRIPTION
**Pull request by sunfishcode**
This is part of an experiment I'm putting together. If you think JSON serialization sounds like a generally desirable thing to have, we can merge it, but otherwise we can wait until we know how the experiments turn out :-).

### CODE REVIEW

**Comment by mbebenita** [comment]
I think this would be very useful for other tools. Can you emit instructions in a form that doesn't require a consumer to parse them. For example, currently you emit:

```
{"instruction":"v5 = imul_imm v4, 4"}
```
would it make more sense to emit

```
{"instruction":["v5", "imul_imm", "v4", 4]}
```

**Comment by bjorn3** [comment]
You could use serde + serde_json for serialization.

**Comment by mbebenita** [comment]
On second thought, perhaps we should stick to a single textual IR representation and write parsers in each tool that needs to use it.

**Comment by sunfishcode** [comment]
The serde + serde_json scheme sounds like it could be a good idea. It'll take a little more work to implement, because Cretonne's EntityLists aren't serde-friendly, but I think we could make it work by creating a separate set of data structures which would be a kind of a "display-form" IR where everything is expanded, that you could easily translate into from the regular "optimized" IR, and which could easily implement serde's Serialize, and have nicer Debug methods. Possibly we could do deserialization this way too.

**Comment by stoklund** [comment]
At a minimum, I think it should live in a separate crate in the `lib/` directory, like the parser. That way, you don't have to pay for it unless you use it. I also try to keep the main `cretonne` crate free of external dependencies.

The immediate operands on instructions are 64-bit integers and IEEE floats including all NaN bit-patterns. As I understand it, JSON can't represent either of those except as strings, so it may not be the best general format for this?

I try to keep to a minimum the number of large switches over the instruction formats. We still have to add new instruction formats somewhat frequently, and each switch adds to the work required. Whenever possible, I use existing functions such as `dfg.inst_args(inst)` and `analyze_branch` to avoid a format switch. Other code, like the `InstBuilder` is generated.

I'm not very familiar with serde, it sounds like it could be useful. But again, I do want to control the binary size of the core code generator, so I'd rather not take a dependency on serde from that crate or include a lot of dead serialization code. A cretonne-json crate that depends on serde is just fine.

A more old-school approach is to generate your own serialization code. The Python scripts have detailed knowledge about the `InstructionData` type. Take a look at the `gen_format_constructor()` function in `meta/gen_instr.py`. It generates the `InstBuilder` methods in ` target/debug/build/cretonne-*/out/builder.rs`.

**Comment by sunfishcode** [comment]
For now, I've added a patch which moves the code into a separate crate, just to make sure I know how to do that, and which prints out instructions broken down into their various parts rather than a single string, which should make it a little better for simple experimentation.

I think a cretonne-serde crate sounds like a useful thing to explore after this.

**Comment by sunfishcode** [comment]
Closing; if we implement serialization, it's likely to take a different form.

**Pull request closed without merging**
